In [3]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
from data_processing_pipeline import runProcessingPipeline
import joblib
import os
import json
configs = json.load(open("config.json"))
processing_configs = json.load(open("src/processing_config.json"))

In [4]:
input_df = pd.read_csv(os.path.join(configs['row_write_folder_path'], configs['all_row_data_key']))
input_df.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
0,Andhra Pradesh,Anantapur,Anantapur,Ground Nut Seed,Ground Nut Seed,Medium,2011-01-01,3800.0,3900.0,3850.0,268
1,Andhra Pradesh,Anantapur,Dharmavaram,Groundnut,Local,Medium,2011-01-01,2700.0,2800.0,2750.0,10
2,Andhra Pradesh,Anantapur,Guntakal,Bengal Gram (Gram)(Whole),Gulabi,Medium,2011-01-01,2400.0,2600.0,2500.0,6
3,Andhra Pradesh,Anantapur,Guntakal,Ground Nut Seed,Ground Nut Seed,Medium,2011-01-01,4300.0,4500.0,4400.0,268
4,Andhra Pradesh,Anantapur,Hindupur,Dry Chillies,1st Sort,Medium,2011-01-01,4600.0,6800.0,5750.0,132

In [6]:
from src.s3_operations import S3BucketHandler

s3_handler = S3BucketHandler(
    bucket_name=configs['bucket_name']
)

processed_df = s3_handler.readS3Data(file_key='batch_processed_file_key', nrows=-1)
processed_df.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
0,1,22,154,146,487,3,2011-01-01,0.000004,0.000004,0.000004,268
1,1,22,935,147,724,3,2011-01-01,0.000003,0.000003,0.000003,10
2,1,22,1212,36,498,3,2011-01-01,0.000003,0.000003,0.000003,6
3,1,22,1212,146,487,3,2011-01-01,0.000005,0.000005,0.000005,268
4,1,22,1285,111,12,3,2011-01-01,0.000005,0.000007,0.000006,132

In [8]:
from src.s3_operations import S3BucketHandler

s3_handler = S3BucketHandler(
    bucket_name=configs['bucket_name']
)

processed_data = s3_handler.readS3Data(file_key='batch_processed_file_key', nrows=-1)
processed_data.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
0,1,22,154,146,487,3,2011-01-01,0.000004,0.000004,0.000004,268
1,1,22,935,147,724,3,2011-01-01,0.000003,0.000003,0.000003,10
2,1,22,1212,36,498,3,2011-01-01,0.000003,0.000003,0.000003,6
3,1,22,1212,146,487,3,2011-01-01,0.000005,0.000005,0.000005,268
4,1,22,1285,111,12,3,2011-01-01,0.000005,0.000007,0.000006,132

In [10]:
input_df.shape, processed_data.shape

((30032282, 11), (30032282, 11))

In [21]:
for commodity, label in zip(input_df['Commodity'].unique(), processed_data['Commodity'].unique()):
    temp_data = processed_data[processed_data['Commodity'] == label]
    save_path = os.path.join('commodity_wise_data/', commodity.replace(" ", '_') + '.csv')
    print("Saving file ", save_path)
    s3_handler.appendToS3StreamCSV(file_key=save_path, new_data_df=temp_data)

Saving file  commodity_wise_data/Ground_Nut_Seed.csv
Saving file  commodity_wise_data/Groundnut.csv
Saving file  commodity_wise_data/Bengal_Gram_(Gram)(Whole).csv
Saving file  commodity_wise_data/Dry_Chillies.csv
Saving file  commodity_wise_data/Tamarind_Fruit.csv
Saving file  commodity_wise_data/Sunflower.csv
Saving file  commodity_wise_data/Paddy_(Dhan)(Common).csv
Saving file  commodity_wise_data/Cotton.csv
Saving file  commodity_wise_data/Jowar_(Sorghum).csv
Saving file  commodity_wise_data/Maize.csv
Saving file  commodity_wise_data/Gur_(Jaggery).csv
Saving file  commodity_wise_data/Tomato.csv
Saving file  commodity_wise_data/Groundnut_(Split).csv
Saving file  commodity_wise_data/Sunflower_Seed.csv
Saving file  commodity_wise_data/Turmeric.csv
Saving file  commodity_wise_data/Groundnut_pods_(raw).csv
Saving file  commodity_wise_data/Papaya.csv
Saving file  commodity_wise_data/Coconut.csv
Saving file  commodity_wise_data/Copra.csv
Saving file  commodity_wise_data/Black_Gram_(Urd_Beans)(Whole).csv
Saving file  commodity_wise_data/Banana.csv
Saving file  commodity_wise_data/Bajra_(Pearl_Millet/Cumbu).csv
Saving file  commodity_wise_data/Rice.csv
Saving file  commodity_wise_data/Carrot.csv
Saving file  commodity_wise_data/Potato.csv
Saving file  commodity_wise_data/Green_Gram_(Moong)(Whole).csv
Saving file  commodity_wise_data/Red_Gram.csv
Saving file  commodity_wise_data/Onion.csv
Saving file  commodity_wise_data/Cashewnuts.csv
Saving file  commodity_wise_data/Ragi_(Finger_Millet).csv
Saving file  commodity_wise_data/Beetroot.csv
Saving file  commodity_wise_data/Bitter_gourd.csv
Saving file  commodity_wise_data/Brinjal.csv
Saving file  commodity_wise_data/Cluster_beans.csv
Saving file  commodity_wise_data/Drumstick.csv
Saving file  commodity_wise_data/Snakeguard.csv
Saving file  commodity_wise_data/Yam.csv
Saving file  commodity_wise_data/Cauliflower.csv
Saving file  commodity_wise_data/Raddish.csv
Saving file  commodity_wise_data/Squash_(Chappal_Kadoo).csv
Saving file  commodity_wise_data/Cucumbar_(Kheera).csv
Saving file  commodity_wise_data/French_Beans_(Frasbean).csv
Saving file  commodity_wise_data/Knool_Khol.csv
Saving file  commodity_wise_data/Ginger_(Green).csv
Saving file  commodity_wise_data/Lak_(Teora).csv
Saving file  commodity_wise_data/Soyabean.csv
Saving file  commodity_wise_data/Wheat.csv
Saving file  commodity_wise_data/Mahua.csv
Saving file  commodity_wise_data/Grapes.csv
Saving file  commodity_wise_data/Water_Melon.csv
Saving file  commodity_wise_data/Arecanut_(Betelnut/Supari).csv
Saving file  commodity_wise_data/Banana_-_Green.csv
Saving file  commodity_wise_data/Bhindi_(Ladies_Finger).csv
Saving file  commodity_wise_data/Bottle_gourd.csv
Saving file  commodity_wise_data/Cabbage.csv
Saving file  commodity_wise_data/Colacasia.csv
Saving file  commodity_wise_data/Guar.csv
Saving file  commodity_wise_data/Papaya_(Raw).csv
Saving file  commodity_wise_data/Rat_Tail_Radish_(Mogari).csv
Saving file  commodity_wise_data/Sweet_Potato.csv
Saving file  commodity_wise_data/Toria.csv
Saving file  commodity_wise_data/Yam_(Ratalu).csv
Saving file  commodity_wise_data/Chikoos_(Sapota).csv
Saving file  commodity_wise_data/Guava.csv
Saving file  commodity_wise_data/Pomegranate.csv
Saving file  commodity_wise_data/Coriander_(Leaves).csv
Saving file  commodity_wise_data/Mint_(Pudina).csv
Saving file  commodity_wise_data/Spinach.csv
Saving file  commodity_wise_data/Chilly_Capsicum.csv
Saving file  commodity_wise_data/Methi_(Leaves).csv
Saving file  commodity_wise_data/Moath_Dal.csv
Saving file  commodity_wise_data/Ajwan.csv
Saving file  commodity_wise_data/Cummin_Seed_(Jeera).csv
Saving file  commodity_wise_data/Methi_Seeds.csv
Saving file  commodity_wise_data/Sesamum_(Sesame,Gingelly,Til).csv
Saving file  commodity_wise_data/Onion_Green.csv
Saving file  commodity_wise_data/Arhar_(Tur/Red_Gram)(Whole).csv
Saving file  commodity_wise_data/Big_Gram.csv
Saving file  commodity_wise_data/Marigold_(Calcutta).csv
Saving file  commodity_wise_data/Castor_Seed.csv
Saving file  commodity_wise_data/Mustard.csv
Saving file  commodity_wise_data/Cowpea_(Lobia/Karamani).csv
Saving file  commodity_wise_data/Isabgul_(Psyllium).csv
Saving file  commodity_wise_data/Lemon.csv
Saving file  commodity_wise_data/Surat_Beans_(Papadi).csv
Saving file  commodity_wise_data/Corriander_seed.csv
Saving file  commodity_wise_data/Garlic.csv
Saving file  commodity_wise_data/Tobacco.csv
Saving file  commodity_wise_data/Suva_(Dill_Seed).csv
Saving file  commodity_wise_data/Green_Chilli.csv
Saving file  commodity_wise_data/Elephant_Yam_(Suran).csv
Saving file  commodity_wise_data/Pointed_gourd_(Parval).csv
Saving file  commodity_wise_data/Tinda.csv
Saving file  commodity_wise_data/Turmeric_(raw).csv
Saving file  commodity_wise_data/Cowpea_(Veg).csv
Saving file  commodity_wise_data/Indian_Beans_(Seam).csv
Saving file  commodity_wise_data/Little_gourd_(Kundru).csv
Saving file  commodity_wise_data/Peas_cod.csv
Saving file  commodity_wise_data/Ridgeguard_(Tori).csv
Saving file  commodity_wise_data/Peas_Wet.csv
Saving file  commodity_wise_data/Black_pepper.csv
Saving file  commodity_wise_data/Peas_(Dry).csv
Saving file  commodity_wise_data/Soanf.csv
Saving file  commodity_wise_data/Apple.csv
Saving file  commodity_wise_data/Ber_(Zizyphus/Borehannu).csv
Saving file  commodity_wise_data/Orange.csv
Saving file  commodity_wise_data/Mango_(Raw-Ripe).csv
Saving file  commodity_wise_data/Pegeon_Pea_(Arhar_Fali).csv
Saving file  commodity_wise_data/Round_gourd.csv
Saving file  commodity_wise_data/Ginger_(Dry).csv
Saving file  commodity_wise_data/Kinnow.csv
Saving file  commodity_wise_data/Leafy_Vegetable.csv
Saving file  commodity_wise_data/Sweet_Pumpkin.csv
Saving file  commodity_wise_data/Mousambi_(Sweet_Lime).csv
Saving file  commodity_wise_data/Pineapple.csv
Saving file  commodity_wise_data/Seetapal.csv
Saving file  commodity_wise_data/Cotton_Seed.csv
Saving file  commodity_wise_data/Capsicum.csv
Saving file  commodity_wise_data/Pumpkin.csv
Saving file  commodity_wise_data/Galgal_(Lemon).csv
Saving file  commodity_wise_data/Indian_Colza_(Sarson).csv
Saving file  commodity_wise_data/Turnip.csv
Saving file  commodity_wise_data/Season_Leaves.csv
Saving file  commodity_wise_data/Mashrooms.csv
Saving file  commodity_wise_data/Sugar.csv
Saving file  commodity_wise_data/Dalda.csv
Saving file  commodity_wise_data/Masur_Dal.csv
Saving file  commodity_wise_data/Mustard_Oil.csv
Saving file  commodity_wise_data/Maida_Atta.csv
Saving file  commodity_wise_data/Wheat_Atta.csv
Saving file  commodity_wise_data/Green_Gram_Dal_(Moong_Dal).csv
Saving file  commodity_wise_data/Chili_Red.csv
Saving file  commodity_wise_data/Avare_Dal.csv
Saving file  commodity_wise_data/Foxtail_Millet_(Navane).csv
Saving file  commodity_wise_data/Kulthi_(Horse_Gram).csv
Saving file  commodity_wise_data/Beans.csv
Saving file  commodity_wise_data/Borehannu.csv
Saving file  commodity_wise_data/Chapparad_Avare.csv
Saving file  commodity_wise_data/Green_Avare_(W).csv
Saving file  commodity_wise_data/Karbuja_(Musk_Melon).csv
Saving file  commodity_wise_data/Lime.csv
Saving file  commodity_wise_data/Seemebadnekai.csv
Saving file  commodity_wise_data/Suvarna_Gadde.csv
Saving file  commodity_wise_data/Thondekai.csv
Saving file  commodity_wise_data/Thogrikai.csv
Saving file  commodity_wise_data/Goat.csv
Saving file  commodity_wise_data/Ox.csv
Saving file  commodity_wise_data/She_Buffalo.csv
Saving file  commodity_wise_data/Sheep.csv
Saving file  commodity_wise_data/Alasande_Gram.csv
Saving file  commodity_wise_data/Sajje.csv
Saving file  commodity_wise_data/Tender_Coconut.csv
Saving file  commodity_wise_data/Green_Peas.csv
Saving file  commodity_wise_data/Tamarind_Seed.csv
Saving file  commodity_wise_data/Amaranthus.csv
Saving file  commodity_wise_data/Field_Pea.csv
Saving file  commodity_wise_data/Cloves.csv
Saving file  commodity_wise_data/Long_Melon_(Kakri).csv
Saving file  commodity_wise_data/Cardamoms.csv
Saving file  commodity_wise_data/Mace.csv
Saving file  commodity_wise_data/White_Pumpkin.csv
Saving file  commodity_wise_data/Pepper_ungarbled.csv
Saving file  commodity_wise_data/Barley_(Jau).csv
Saving file  commodity_wise_data/Coffee.csv
Saving file  commodity_wise_data/Tapioca.csv
Saving file  commodity_wise_data/Ashgourd.csv
Saving file  commodity_wise_data/Rubber.csv
Saving file  commodity_wise_data/Amphophalus.csv
Saving file  commodity_wise_data/Other_Pulses.csv
Saving file  commodity_wise_data/Kabuli_Chana_(Chickpeas-White).csv
Saving file  commodity_wise_data/Same/Savi.csv
Saving file  commodity_wise_data/Lentil_(Masur)(Whole).csv
Saving file  commodity_wise_data/Cow.csv
Saving file  commodity_wise_data/He_Buffalo.csv
Saving file  commodity_wise_data/Kakada.csv
Saving file  commodity_wise_data/Dry_Grapes.csv
Saving file  commodity_wise_data/Mataki.csv
Saving file  commodity_wise_data/Cock.csv
Saving file  commodity_wise_data/Fish.csv
Saving file  commodity_wise_data/BOP.csv
Saving file  commodity_wise_data/Chrysanthemum_(Loose).csv
Saving file  commodity_wise_data/Jarbara.csv
Saving file  commodity_wise_data/Khoya.csv
Saving file  commodity_wise_data/Hen.csv
Saving file  commodity_wise_data/Bull.csv
Saving file  commodity_wise_data/Wool.csv
Saving file  commodity_wise_data/Taramira.csv
Saving file  commodity_wise_data/Rose_(Loose)).csv
Saving file  commodity_wise_data/Neem_Seed.csv
Saving file  commodity_wise_data/Ghee.csv
Saving file  commodity_wise_data/Linseed.csv
Saving file  commodity_wise_data/Wood.csv
Saving file  commodity_wise_data/Dhaincha.csv
Saving file  commodity_wise_data/Jute.csv
Saving file  commodity_wise_data/Betal_Leaves.csv
Saving file  commodity_wise_data/Mahua_Seed_(Hippe_seed).csv
Saving file  commodity_wise_data/Niger_Seed_(Ramtil).csv
Saving file  commodity_wise_data/Gram_Raw_(Chholia).csv
Saving file  commodity_wise_data/Pear_(Marasebu).csv
Saving file  commodity_wise_data/Beaten_Rice.csv
Saving file  commodity_wise_data/Safflower.csv
Saving file  commodity_wise_data/Carnation.csv
Saving file  commodity_wise_data/Rose_(Tata).csv
Saving file  commodity_wise_data/Amla_(Nelli_Kai).csv
Saving file  commodity_wise_data/Jamamkhan.csv
Saving file  commodity_wise_data/Balekai.csv
Saving file  commodity_wise_data/Tube_Flower.csv
Saving file  commodity_wise_data/Calf.csv
Saving file  commodity_wise_data/She_Goat.csv
Saving file  commodity_wise_data/Duck.csv
Saving file  commodity_wise_data/Cashew_Kernnel.csv
Saving file  commodity_wise_data/Jack_Fruit.csv
Saving file  commodity_wise_data/Lotus_Sticks.csv
Saving file  commodity_wise_data/Walnut.csv
Saving file  commodity_wise_data/Tea.csv
Saving file  commodity_wise_data/Soji.csv
Saving file  commodity_wise_data/Chennangi_Dal.csv
Saving file  commodity_wise_data/Bunch_Beans.csv
Saving file  commodity_wise_data/Coconut_Oil.csv
Saving file  commodity_wise_data/Gingelly_Oil.csv
Saving file  commodity_wise_data/Mango.csv
Saving file  commodity_wise_data/Gramflour.csv
Saving file  commodity_wise_data/Anthorium.csv
Saving file  commodity_wise_data/Dry_Fodder.csv
Saving file  commodity_wise_data/Thinai_(Italian_Millet).csv
Saving file  commodity_wise_data/Coconut_Seed.csv
Saving file  commodity_wise_data/Hybrid_Cumbu.csv
Saving file  commodity_wise_data/T.V._Cumbu.csv
Saving file  commodity_wise_data/Kodo_Millet_(Varagu).csv
Saving file  commodity_wise_data/Raya.csv
Saving file  commodity_wise_data/Jasmine.csv
Saving file  commodity_wise_data/Pepper_garbled.csv
Saving file  commodity_wise_data/Peach.csv
Saving file  commodity_wise_data/Broken_Rice.csv
Saving file  commodity_wise_data/Chow_Chow.csv
Saving file  commodity_wise_data/Sponge_gourd.csv
Saving file  commodity_wise_data/Nutmeg.csv
Saving file  commodity_wise_data/Rose_(Local).csv
Saving file  commodity_wise_data/Ram.csv
Saving file  commodity_wise_data/Gladiolus_Cut_Flower.csv
Saving file  commodity_wise_data/Lilly.csv
Saving file  commodity_wise_data/Orchid.csv
Saving file  commodity_wise_data/Soapnut_(Antawala/Retha).csv
Saving file  commodity_wise_data/Pigs.csv
Saving file  commodity_wise_data/Rajgir.csv
Saving file  commodity_wise_data/Ambada_Seed.csv
Saving file  commodity_wise_data/Skin_And_Hide.csv
Saving file  commodity_wise_data/Honge_seed.csv
Saving file  commodity_wise_data/Sugarcane.csv
Saving file  commodity_wise_data/Bran.csv
Saving file  commodity_wise_data/Egg.csv
Saving file  commodity_wise_data/Javi.csv
Saving file  commodity_wise_data/Litchi.csv
Saving file  commodity_wise_data/Lint.csv
Saving file  commodity_wise_data/Nelli_Kai.csv
Saving file  commodity_wise_data/Binoula.csv
Saving file  commodity_wise_data/Sunhemp.csv
Saving file  commodity_wise_data/Hippe_Seed.csv
Saving file  commodity_wise_data/Bullar.csv
Saving file  commodity_wise_data/Firewood.csv
Saving file  commodity_wise_data/Duster_Beans.csv
Saving file  commodity_wise_data/Karamani.csv
Saving file  commodity_wise_data/Tube_Rose_(Single).csv
Saving file  commodity_wise_data/Ground_Nut_Oil.csv
Saving file  commodity_wise_data/Alsandikai.csv
Saving file  commodity_wise_data/Plum.csv
Saving file  commodity_wise_data/Millets.csv
Saving file  commodity_wise_data/Green_Fodder.csv
Saving file  commodity_wise_data/Bamboo.csv
Saving file  commodity_wise_data/Maragensu.csv
Saving file  commodity_wise_data/Cane.csv
Saving file  commodity_wise_data/Cherry.csv
Saving file  commodity_wise_data/Chakotha.csv
Saving file  commodity_wise_data/Butter.csv
Saving file  commodity_wise_data/Lukad.csv
Saving file  commodity_wise_data/Antawala.csv
Saving file  commodity_wise_data/Almond_(Badam).csv
Saving file  commodity_wise_data/Apricot_(Jardalu/Khumani).csv
Saving file  commodity_wise_data/Sabu_Dan.csv
Saving file  commodity_wise_data/Suram.csv
Saving file  commodity_wise_data/Jamun_(Narale_Hannu).csv
Saving file  commodity_wise_data/Kartali_(Kantola).csv
Saving file  commodity_wise_data/Sarasum.csv
Saving file  commodity_wise_data/Gurellu.csv
Saving file  commodity_wise_data/Pundi.csv
Saving file  commodity_wise_data/Marasebu.csv
Saving file  commodity_wise_data/Custard_Apple_(Sharifa).csv
Saving file  commodity_wise_data/Persimon_(Japani_Fal).csv
Saving file  commodity_wise_data/Egypian_Clover_(Barseem).csv
Saving file  commodity_wise_data/Bay_leaf_(Tejpatta).csv
Saving file  commodity_wise_data/Broomstick_(Flower_Broom).csv
Saving file  commodity_wise_data/Siddota.csv
Saving file  commodity_wise_data/Kuchur.csv
Saving file  commodity_wise_data/Pundi_Seed.csv
Saving file  commodity_wise_data/Jute_Seed.csv
Saving file  commodity_wise_data/Torchwood.csv
Saving file  commodity_wise_data/Kankambra.csv
Saving file  commodity_wise_data/Bengal_Gram_Dal_(Chana_Dal).csv
Saving file  commodity_wise_data/Castor_Oil.csv
Saving file  commodity_wise_data/Nearle_Hannu.csv
Saving file  commodity_wise_data/Arhar_Dal_(Tur_Dal).csv
Saving file  commodity_wise_data/Chennangi_(Whole).csv
Saving file  commodity_wise_data/Cocoa.csv
Saving file  commodity_wise_data/Black_Gram_Dal_(Urd_Dal).csv
Saving file  commodity_wise_data/Astera.csv
Saving file  commodity_wise_data/Gladiolus_Bulb.csv
Saving file  commodity_wise_data/Dal_(Avare).csv
Saving file  commodity_wise_data/Resinwood.csv
Saving file  commodity_wise_data/Daila_(Chandni).csv
Saving file  commodity_wise_data/Kharif_Mash.csv
Saving file  commodity_wise_data/Kacholam.csv
Saving file  commodity_wise_data/Guar_Seed_(Cluster_Beans_Seed).csv
Saving file  commodity_wise_data/Chrysanthemum.csv
Saving file  commodity_wise_data/Raibel.csv
Saving file  commodity_wise_data/Tube_Rose_(Double).csv
Saving file  commodity_wise_data/Marget.csv
Saving file  commodity_wise_data/Marigold_(loose).csv
Saving file  commodity_wise_data/Patti_Calcutta.csv
Saving file  commodity_wise_data/Tube_Rose_(Loose).csv
Saving file  commodity_wise_data/Jaffri.csv
Saving file  commodity_wise_data/Lotus.csv
Saving file  commodity_wise_data/White_Peas.csv
Saving file  commodity_wise_data/Mahedi.csv
Saving file  commodity_wise_data/Coca.csv
Saving file  commodity_wise_data/Myrobolan_(Harad).csv
Saving file  commodity_wise_data/Flower_Broom.csv
Saving file  commodity_wise_data/Delha.csv
Saving file  commodity_wise_data/Haralekai.csv
Saving file  commodity_wise_data/Paddy_(Dhan)(Basmati).csv
Saving file  commodity_wise_data/Cinamon_(Dalchini).csv
Saving file  commodity_wise_data/Sompu.csv
Saving file  commodity_wise_data/Honey.csv
Saving file  commodity_wise_data/buttery.csv
Saving file  commodity_wise_data/Saffron.csv
Saving file  commodity_wise_data/Ashwagandha.csv
Saving file  commodity_wise_data/Asalia.csv
Saving file  commodity_wise_data/dried_mango.csv
Saving file  commodity_wise_data/Kutki.csv
Saving file  commodity_wise_data/Other_green_and_fresh_vegetables.csv
Saving file  commodity_wise_data/Fig_(Anjura/Anjeer).csv
Saving file  commodity_wise_data/mango_powder.csv
Saving file  commodity_wise_data/gulli.csv
Saving file  commodity_wise_data/basil.csv
Saving file  commodity_wise_data/nigella_seeds.csv
Saving file  commodity_wise_data/poppy_seeds.csv
Saving file  commodity_wise_data/karanja_seeds.csv
Saving file  commodity_wise_data/dhawai_flowers.csv
Saving file  commodity_wise_data/Pupadia.csv
Saving file  commodity_wise_data/Giloy.csv
Saving file  commodity_wise_data/Asparagus.csv
Saving file  commodity_wise_data/Muesli.csv
Saving file  commodity_wise_data/Brahmi.csv
Saving file  commodity_wise_data/Absinthe.csv
Saving file  commodity_wise_data/White_Muesli.csv